import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { Parisienne } from 'next/font/google';
import { BackgroundIcons } from '@/components/common';
import './globals.css';

const neoDgm = localFont({
  src: './fonts/neodgm.woff',
  variable: '--font-neodgm',
  weight: '100 900',
});
const parisienne = Parisienne({ weight: '400', subsets: ['latin'] });

export const metadata: Metadata = {
  title: '산타 우체통',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${neoDgm.variable} antialiased`}>
        <main>
          <section>
            <h1
              className={`${parisienne.className} mt-5 text-[40px] text-center lg:text-[110px]`}
            >
              Merry Christmas
            </h1>
            {children}
            <BackgroundIcons />
          </section>
        </main>
      </body>
    </html>
  );
}
