import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Providers from './providers';
import { Layout } from '@/components/common';
import { ToastMessageContainer } from '@/components/ui';
import './globals.css';

const neoDgm = localFont({
  src: './fonts/neodgm.woff',
  variable: '--font-neodgm',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: '산타 우체통',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${neoDgm.variable} antialiased`}>
        <Providers>
          <Layout>{children}</Layout>
          <ToastMessageContainer />
        </Providers>
      </body>
    </html>
  );
}
